# Generated by Django 6.0.6 on 2026-06-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('delivery', 'On-Demand Delivery'), ('maintenance', 'Home Maintenance & Repair'), ('creative', 'Freelance & Creative'), ('legal', 'Professional/Legal Services')], default='delivery', max_length=30)),
                ('budget', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('searching', 'Searching Contractors'), ('offered', 'Offered'), ('active', 'Active (Signed)'), ('completed', 'Completed by Contractor'), ('approved', 'Approved & Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('terms_text', models.TextField()),
                ('client_signature', models.TextField(blank=True, null=True)),
                ('contractor_signature', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('job_latitude', models.FloatField(default=23.0225)),
                ('job_longitude', models.FloatField(default=72.5714)),
                ('contractor_latitude', models.FloatField(blank=True, null=True)),
                ('contractor_longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
