# Generated by Django 6.0.6 on 2026-07-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_current_matching_contractor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='client_attachment_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='client_attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor_attachment_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor_attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
