# Generated by Django 5.0.14 on 2026-07-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_client_attachment_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='client_attachment_data',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='client_attachment_name',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contractor_attachment_data',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contractor_attachment_name',
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
