# Generated by Django 6.0.7 on 2026-07-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contract_accepted_contractors_alter_contract_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='duration',
            field=models.CharField(blank=True, default='1 Day', max_length=50),
        ),
    ]
