# Generated by Django 6.0.6 on 2026-07-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_contract_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='predicted_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
