# Generated by Django 6.0.6 on 2026-07-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_contract_predicted_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='area_sqft',
            field=models.FloatField(blank=True, default=1000.0),
        ),
    ]
