# Generated by Django 6.0.7 on 2026-07-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_contract_area_sqft'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
