# Generated by Django 6.0.7 on 2026-07-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_contract_specifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='specifications',
        ),
        migrations.AddField(
            model_name='contract',
            name='dynamic_attributes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='sub_service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
