# Generated by Django 6.0.6 on 2026-07-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_balance',
            field=models.FloatField(default=10000.0),
        ),
    ]
