# Generated by Django 6.0.6 on 2026-07-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.FloatField(default=23.0225),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.FloatField(default=72.5714),
        ),
    ]
